# Generated by Django 3.2.8 on 2022-06-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='location',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
