# Generated by Django 3.2.8 on 2022-06-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_auto_20220602_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='location',
            new_name='locationn',
        ),
    ]
