# Generated by Django 3.2.8 on 2022-06-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_auto_20220602_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='participants',
            new_name='participnts',
        ),
    ]
