# Generated by Django 3.2.8 on 2022-06-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_rename_participants_meetup_participnts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='participnts',
        ),
        migrations.AddField(
            model_name='meetup',
            name='participantss',
            field=models.ManyToManyField(blank=True, null=True, to='meetups.Participant'),
        ),
    ]
