# Generated by Django 4.0.4 on 2022-06-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0010_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'User Details'},
        ),
    ]
