# Generated by Django 4.0.4 on 2022-06-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='title',
            new_name='titlee',
        ),
    ]
