# Generated by Django 4.0.4 on 2022-06-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_rename_title_snippet_titlee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='titlee',
            new_name='title',
        ),
    ]
